version: 2.1

executors:
  base:
    docker:
      - image: cimg/python:3.9

parameters:
  image1:
    type: string
    default: ''
#   image1_str:
#     type: string
#     default: notreal
  image2:
    type: boolean
    default: false
    
jobs:
  project_one:
      executor: base
      steps:
        - run: 
            command: |
              echo << pipeline.parameters.image1 >>
              echo << pipeline.parameters.image2 >>
              echo << pipeline.git.branch >>           
              
workflows:
  build-1:
    when: 
      or: 
        - << pipeline.parameters.image1 >>
        - << pipeline.parameters.image2 >> 
    jobs:
      - project_one
