version: 2.1

executors:
  base:
    docker:
      - image: cimg/python:3.9

parameters:
  image1:
    type: boolean
    default: false
  image2:
    type: boolean
    default: false
    
jobs:
  project_one:
      executor: base
      steps:
        - run: 
            command: |
              echo "img one"
              
  project_two: 
      executor: base
      steps:
        - run: 
            command: |
              echo "img two" 
              
  all_projects: 
      executor: base
      steps:
        - run: 
            command: |
              echo "all"   
              
workflows:
  build-1:
    when: 
      or: 
        - << pipeline.parameters.image1 >>
    jobs:
      - project_one
      
  build-2:
    when: 
      or: 
        - << pipeline.parameters.image2 >>  
    jobs:
      - project_two
