version: 2.1

executors:
  base:
    docker:
      - image: cimg/python:3.9

parameters:
  image1:
    type: boolean
    default: false
  image1_str:
    type: string
    default: notreal
  image2:
    type: boolean
    default: false
    
jobs:
  project_one:
      executor: base
      steps:
        - run: 
            command: |
              echo "img one"
              echo << pipeline.parameters.image1 >>
              echo << pipeline.parameters.image1_str >>
              echo << pipeline.parameters.image2 >>
              echo << pipeline.git.branch >>           
              
workflows:
  build-1:
    jobs:
      - project_one
